"""Add api_token to user

Revision ID: 3d7dfe580c58
Revises: df45154513da
Create Date: 2026-02-20 10:02:50.129280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7dfe580c58'
down_revision = 'df45154513da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_api_token'), ['api_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_token'))
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
