"""add seating tables

Revision ID: 3ed8901df1ff
Revises: b2c3d4e5f6a8
Create Date: 2026-03-30 08:03:07.146475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed8901df1ff'
down_revision = 'b2c3d4e5f6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seating_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seating_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seating_table_event_id'), ['event_id'], unique=False)

    op.create_table('seat_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('seat_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitation.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['seating_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_id', name='uq_seat_invitation')
    )
    with op.batch_alter_table('seat_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_assignment_invitation_id'), ['invitation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_assignment_table_id'), ['table_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_assignment_table_id'))
        batch_op.drop_index(batch_op.f('ix_seat_assignment_invitation_id'))

    op.drop_table('seat_assignment')
    with op.batch_alter_table('seating_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seating_table_event_id'))

    op.drop_table('seating_table')
    # ### end Alembic commands ###
