"""add per-event guest attributes

Each event can define named attributes (e.g. "Hunting") with a fixed list of
options (e.g. Hunter / Follower). Every guest on that event may be set to one
option per attribute; no row means "not set".

These belong to the event, not to the friends database: the same person can be a
Hunter at one event and a Follower at the next.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'j4k5l6m7n8o9'
down_revision = 'i3j4k5l6m7n8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_event_attribute_name')
    )
    with op.batch_alter_table('event_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_attribute_event_id'), ['event_id'], unique=False)

    op.create_table('event_attribute_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['event_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_id', 'label', name='uq_event_attribute_option_label')
    )
    with op.batch_alter_table('event_attribute_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_attribute_option_attribute_id'), ['attribute_id'], unique=False)

    op.create_table('invitation_attribute_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['event_attribute.id'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitation.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['event_attribute_option.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_id', 'attribute_id', name='uq_invitation_attribute')
    )
    with op.batch_alter_table('invitation_attribute_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitation_attribute_value_attribute_id'), ['attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_attribute_value_invitation_id'), ['invitation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_attribute_value_option_id'), ['option_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation_attribute_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitation_attribute_value_option_id'))
        batch_op.drop_index(batch_op.f('ix_invitation_attribute_value_invitation_id'))
        batch_op.drop_index(batch_op.f('ix_invitation_attribute_value_attribute_id'))

    op.drop_table('invitation_attribute_value')
    with op.batch_alter_table('event_attribute_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_attribute_option_attribute_id'))

    op.drop_table('event_attribute_option')
    with op.batch_alter_table('event_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_attribute_event_id'))

    op.drop_table('event_attribute')
    # ### end Alembic commands ###
