from datetime import date, datetime
from rsvp_manager.extensions import db
from rsvp_manager.models import Event, Guest, Invitation


def seed(user_id):
    """Populate a user's account with sample data."""
    today = date.today()
    events = [
        Event(user_id=user_id, name="New Year's Eve Bash", event_type="Party", location="Rooftop Lounge, Miami", date=date(2025, 12, 31), date_created=date(2025, 11, 15), notes="Great turnout!", target_attendees=20),
        Event(user_id=user_id, name="Q4 Board Meeting", event_type="Corporate", location="HQ Boardroom, Chicago", date=date(2026, 1, 15), date_created=date(2025, 12, 1), notes="Quarterly review completed"),
        Event(user_id=user_id, name="Valentine's Dinner", event_type="Dinner", location="Le Petit Bistro, Paris", date=date(2026, 2, 14), date_created=date(2026, 1, 10), notes="Intimate dinner for couples", target_attendees=8),
        Event(user_id=user_id, name="Annual Gala Dinner", event_type="Dinner", location="Grand Hotel, New York", date=date(2026, 4, 12), date_created=today, notes="Black tie event", target_attendees=10),
        Event(user_id=user_id, name="Team Building Retreat", event_type="Corporate", location="Lakehouse Resort, Vermont", date=date(2026, 5, 20), date_created=today, notes="Outdoor activities planned", target_attendees=6),
        Event(user_id=user_id, name="Summer Garden Party", event_type="Party", location="Riverside Park, Boston", date=date(2026, 7, 4), date_created=today, notes="Casual dress code"),
        Event(user_id=user_id, name="Lake House Weekend", event_type="Weekend", location="Lakehouse Resort, Vermont", date=date(2026, 8, 22), date_created=today, notes="Arrive Friday evening, depart Sunday", target_attendees=15),
        Event(user_id=user_id, name="Fall Pheasant Hunt", event_type="Hunt", location="Highland Estate, Montana", date=date(2026, 9, 15), date_created=today, notes="Bring warm layers", target_attendees=4),
    ]
    db.session.add_all(events)
    db.session.flush()

    now = datetime.now()
    guests = [
        Guest(user_id=user_id, first_name="Alice", last_name="Martin", gender="Female", notes="Vegetarian", date_created=now),
        Guest(user_id=user_id, first_name="James", last_name="Wilson", gender="Male", date_created=now),
        Guest(user_id=user_id, first_name="Sofia", last_name="Garcia", gender="Female", notes="Plus one confirmed", date_created=now),
        Guest(user_id=user_id, first_name="Oliver", last_name="Brown", gender="Male", date_created=now),
        Guest(user_id=user_id, first_name="Emma", last_name="Taylor", gender="Female", date_created=now),
        Guest(user_id=user_id, first_name="William", last_name="Anderson", gender="Male", notes="Allergic to nuts", date_created=now),
        Guest(user_id=user_id, first_name="Charlotte", last_name="Thomas", gender="Female", date_created=now),
        Guest(user_id=user_id, first_name="Henry", last_name="Jackson", gender="Male", date_created=now),
        Guest(user_id=user_id, first_name="Amelia", last_name="White", gender="Female", notes="Wheelchair accessible seating", date_created=now),
        Guest(user_id=user_id, first_name="Lucas", last_name="Harris", gender="Male", date_created=now),
        Guest(user_id=user_id, first_name="Isabella", last_name="Clark", gender="Female", date_created=now),
        Guest(user_id=user_id, first_name="Benjamin", last_name="Lee", gender="Male", notes="VIP", date_created=now),
        Guest(user_id=user_id, first_name="Mia", last_name="Robinson", gender="Female", date_created=now),
        Guest(user_id=user_id, first_name="Ethan", last_name="Wright", gender="Male", notes="Prefers window seat", date_created=now),
        Guest(user_id=user_id, first_name="Ava", last_name="Lopez", gender="Female", notes="Gluten-free", date_created=now),
        Guest(user_id=user_id, first_name="Noah", last_name="Mitchell", gender="Male", date_created=now),
        Guest(user_id=user_id, first_name="Lily", last_name="Perez", gender="Female", date_created=now),
        Guest(user_id=user_id, first_name="Daniel", last_name="Roberts", gender="Male", notes="Board member", date_created=now),
        Guest(user_id=user_id, first_name="Grace", last_name="Turner", gender="Female", date_created=now),
        Guest(user_id=user_id, first_name="Jack", last_name="Phillips", gender="Male", date_created=now),
        Guest(user_id=user_id, first_name="Chloe", last_name="Campbell", gender="Female", notes="Bringing plus one", date_created=now),
        Guest(user_id=user_id, first_name="Ryan", last_name="Parker", gender="Male", date_created=now),
        Guest(user_id=user_id, first_name="Zoe", last_name="Evans", gender="Female", date_created=now),
        Guest(user_id=user_id, first_name="Nathan", last_name="Collins", gender="Male", notes="Photographer", date_created=now),
        Guest(user_id=user_id, first_name="Hannah", last_name="Stewart", gender="Female", date_created=now),
    ]
    db.session.add_all(guests)
    db.session.flush()

    invitations = [
        Invitation(event_id=events[0].id, guest_id=guests[0].id, status="Attending", channel="Email", date_invited=date(2025, 11, 20), date_responded=date(2025, 11, 25)),
        Invitation(event_id=events[0].id, guest_id=guests[1].id, status="Attending", channel="WhatsApp", date_invited=date(2025, 11, 20), date_responded=date(2025, 11, 22)),
        Invitation(event_id=events[0].id, guest_id=guests[2].id, status="Attending", channel="Email", date_invited=date(2025, 11, 20), date_responded=date(2025, 12, 1)),
        Invitation(event_id=events[0].id, guest_id=guests[4].id, status="Attending", channel="SMS", date_invited=date(2025, 11, 25), date_responded=date(2025, 11, 28)),
        Invitation(event_id=events[0].id, guest_id=guests[6].id, status="Declined", channel="Email", date_invited=date(2025, 11, 20), date_responded=date(2025, 11, 30), notes="Out of town"),
        Invitation(event_id=events[0].id, guest_id=guests[8].id, status="Attending", channel="Live", date_invited=date(2025, 11, 25), date_responded=date(2025, 11, 26)),
        Invitation(event_id=events[0].id, guest_id=guests[12].id, status="Attending", channel="WhatsApp", date_invited=date(2025, 12, 1), date_responded=date(2025, 12, 5)),
        Invitation(event_id=events[0].id, guest_id=guests[14].id, status="Attending", channel="Email", date_invited=date(2025, 12, 1), date_responded=date(2025, 12, 3)),
        Invitation(event_id=events[0].id, guest_id=guests[16].id, status="Declined", channel="Call", date_invited=date(2025, 12, 1), date_responded=date(2025, 12, 10)),
        Invitation(event_id=events[0].id, guest_id=guests[19].id, status="Attending", channel="Email", date_invited=date(2025, 12, 5), date_responded=date(2025, 12, 8)),
        Invitation(event_id=events[0].id, guest_id=guests[20].id, status="Attending", channel="SMS", date_invited=date(2025, 12, 5), date_responded=date(2025, 12, 9)),
        Invitation(event_id=events[0].id, guest_id=guests[23].id, status="Attending", channel="Email", date_invited=date(2025, 12, 5), date_responded=date(2025, 12, 7), notes="Taking photos"),
        Invitation(event_id=events[1].id, guest_id=guests[1].id, status="Attending", channel="Email", date_invited=date(2025, 12, 10), date_responded=date(2025, 12, 12)),
        Invitation(event_id=events[1].id, guest_id=guests[5].id, status="Attending", channel="Email", date_invited=date(2025, 12, 10), date_responded=date(2025, 12, 11)),
        Invitation(event_id=events[1].id, guest_id=guests[17].id, status="Attending", channel="Email", date_invited=date(2025, 12, 10), date_responded=date(2025, 12, 13), notes="Presenting Q4 numbers"),
        Invitation(event_id=events[1].id, guest_id=guests[3].id, status="Declined", channel="Email", date_invited=date(2025, 12, 10), date_responded=date(2025, 12, 15)),
        Invitation(event_id=events[1].id, guest_id=guests[9].id, status="Attending", channel="Call", date_invited=date(2025, 12, 12), date_responded=date(2025, 12, 14)),
        Invitation(event_id=events[1].id, guest_id=guests[15].id, status="Pending", channel="Email", date_invited=date(2025, 12, 15)),
        Invitation(event_id=events[2].id, guest_id=guests[0].id, status="Attending", channel="Email", date_invited=date(2026, 1, 15), date_responded=date(2026, 1, 18)),
        Invitation(event_id=events[2].id, guest_id=guests[1].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 1, 15), date_responded=date(2026, 1, 17)),
        Invitation(event_id=events[2].id, guest_id=guests[2].id, status="Attending", channel="Email", date_invited=date(2026, 1, 15), date_responded=date(2026, 1, 20)),
        Invitation(event_id=events[2].id, guest_id=guests[4].id, status="Attending", channel="Live", date_invited=date(2026, 1, 18), date_responded=date(2026, 1, 19)),
        Invitation(event_id=events[2].id, guest_id=guests[12].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 1, 18), date_responded=date(2026, 1, 22)),
        Invitation(event_id=events[2].id, guest_id=guests[13].id, status="Attending", channel="Email", date_invited=date(2026, 1, 18), date_responded=date(2026, 1, 21)),
        Invitation(event_id=events[2].id, guest_id=guests[18].id, status="Attending", channel="SMS", date_invited=date(2026, 1, 20), date_responded=date(2026, 1, 25)),
        Invitation(event_id=events[2].id, guest_id=guests[20].id, status="Attending", channel="Email", date_invited=date(2026, 1, 20), date_responded=date(2026, 1, 24), notes="Anniversary celebration"),
        Invitation(event_id=events[3].id, guest_id=guests[0].id, status="Attending", channel="Email", date_invited=date(2026, 2, 1), date_responded=date(2026, 2, 5), notes="Confirmed plus one"),
        Invitation(event_id=events[3].id, guest_id=guests[1].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 2, 1), date_responded=date(2026, 2, 3)),
        Invitation(event_id=events[3].id, guest_id=guests[2].id, status="Pending", channel="Email", date_invited=date(2026, 2, 1)),
        Invitation(event_id=events[3].id, guest_id=guests[3].id, status="Declined", channel="Call", date_invited=date(2026, 2, 1), date_responded=date(2026, 2, 10), notes="Travel conflict"),
        Invitation(event_id=events[3].id, guest_id=guests[4].id, status="Attending", channel="Email", date_invited=date(2026, 2, 5), date_responded=date(2026, 2, 8)),
        Invitation(event_id=events[3].id, guest_id=guests[8].id, status="Attending", channel="Live", date_invited=date(2026, 2, 5), date_responded=date(2026, 2, 7)),
        Invitation(event_id=events[3].id, guest_id=guests[10].id, status="Not Sent"),
        Invitation(event_id=events[3].id, guest_id=guests[11].id, status="Attending", channel="Email", date_invited=date(2026, 2, 1), date_responded=date(2026, 2, 2), notes="VIP table"),
        Invitation(event_id=events[3].id, guest_id=guests[14].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 2, 8), date_responded=date(2026, 2, 12)),
        Invitation(event_id=events[3].id, guest_id=guests[21].id, status="Pending", channel="Email", date_invited=date(2026, 2, 10)),
        Invitation(event_id=events[4].id, guest_id=guests[1].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 3, 1), date_responded=date(2026, 3, 5)),
        Invitation(event_id=events[4].id, guest_id=guests[3].id, status="Attending", channel="Email", date_invited=date(2026, 3, 1), date_responded=date(2026, 3, 4)),
        Invitation(event_id=events[4].id, guest_id=guests[5].id, status="Pending", channel="Call", date_invited=date(2026, 3, 1), notes="Call back tomorrow"),
        Invitation(event_id=events[4].id, guest_id=guests[7].id, status="Declined", channel="WhatsApp", date_invited=date(2026, 3, 1), date_responded=date(2026, 3, 8)),
        Invitation(event_id=events[4].id, guest_id=guests[9].id, status="Not Sent"),
        Invitation(event_id=events[4].id, guest_id=guests[11].id, status="Not Sent"),
        Invitation(event_id=events[4].id, guest_id=guests[15].id, status="Attending", channel="Email", date_invited=date(2026, 3, 5), date_responded=date(2026, 3, 7)),
        Invitation(event_id=events[4].id, guest_id=guests[19].id, status="Attending", channel="SMS", date_invited=date(2026, 3, 5), date_responded=date(2026, 3, 9)),
        Invitation(event_id=events[5].id, guest_id=guests[0].id, status="Attending", channel="Live", date_invited=date(2026, 4, 1), date_responded=date(2026, 4, 3)),
        Invitation(event_id=events[5].id, guest_id=guests[2].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 4, 1), date_responded=date(2026, 4, 2)),
        Invitation(event_id=events[5].id, guest_id=guests[4].id, status="Pending", channel="Email", date_invited=date(2026, 4, 5)),
        Invitation(event_id=events[5].id, guest_id=guests[6].id, status="Attending", channel="SMS", date_invited=date(2026, 4, 1), date_responded=date(2026, 4, 4)),
        Invitation(event_id=events[5].id, guest_id=guests[8].id, status="Declined", channel="Call", date_invited=date(2026, 4, 1), date_responded=date(2026, 4, 7), notes="Health reasons"),
        Invitation(event_id=events[5].id, guest_id=guests[16].id, status="Attending", channel="Email", date_invited=date(2026, 4, 8), date_responded=date(2026, 4, 10)),
        Invitation(event_id=events[5].id, guest_id=guests[22].id, status="Not Sent"),
        Invitation(event_id=events[6].id, guest_id=guests[0].id, status="Attending", channel="Email", date_invited=date(2026, 5, 1), date_responded=date(2026, 5, 5)),
        Invitation(event_id=events[6].id, guest_id=guests[2].id, status="Attending", channel="Email", date_invited=date(2026, 5, 1), date_responded=date(2026, 5, 3)),
        Invitation(event_id=events[6].id, guest_id=guests[4].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 5, 1), date_responded=date(2026, 5, 4)),
        Invitation(event_id=events[6].id, guest_id=guests[6].id, status="Pending", channel="Email", date_invited=date(2026, 5, 1)),
        Invitation(event_id=events[6].id, guest_id=guests[8].id, status="Attending", channel="Live", date_invited=date(2026, 5, 5), date_responded=date(2026, 5, 6)),
        Invitation(event_id=events[6].id, guest_id=guests[10].id, status="Attending", channel="Email", date_invited=date(2026, 5, 5), date_responded=date(2026, 5, 9)),
        Invitation(event_id=events[6].id, guest_id=guests[12].id, status="Declined", channel="Call", date_invited=date(2026, 5, 5), date_responded=date(2026, 5, 12), notes="Scheduling conflict"),
        Invitation(event_id=events[6].id, guest_id=guests[14].id, status="Attending", channel="Email", date_invited=date(2026, 5, 8), date_responded=date(2026, 5, 11)),
        Invitation(event_id=events[6].id, guest_id=guests[16].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 5, 8), date_responded=date(2026, 5, 10)),
        Invitation(event_id=events[6].id, guest_id=guests[18].id, status="Not Sent"),
        Invitation(event_id=events[6].id, guest_id=guests[20].id, status="Attending", channel="SMS", date_invited=date(2026, 5, 10), date_responded=date(2026, 5, 14), notes="Bringing plus one"),
        Invitation(event_id=events[6].id, guest_id=guests[22].id, status="Pending", channel="Email", date_invited=date(2026, 5, 10)),
        Invitation(event_id=events[6].id, guest_id=guests[23].id, status="Attending", channel="Email", date_invited=date(2026, 5, 1), date_responded=date(2026, 5, 2), notes="Bringing kayak"),
        Invitation(event_id=events[6].id, guest_id=guests[24].id, status="Attending", channel="WhatsApp", date_invited=date(2026, 5, 10), date_responded=date(2026, 5, 13)),
        Invitation(event_id=events[7].id, guest_id=guests[5].id, status="Not Sent"),
        Invitation(event_id=events[7].id, guest_id=guests[7].id, status="Not Sent"),
        Invitation(event_id=events[7].id, guest_id=guests[9].id, status="Attending", channel="Email", date_invited=date(2026, 5, 1), date_responded=date(2026, 5, 3)),
        Invitation(event_id=events[7].id, guest_id=guests[11].id, status="Attending", channel="Email", date_invited=date(2026, 5, 1), date_responded=date(2026, 5, 2), notes="Bringing own gear"),
        Invitation(event_id=events[7].id, guest_id=guests[17].id, status="Attending", channel="Call", date_invited=date(2026, 5, 5), date_responded=date(2026, 5, 8)),
        Invitation(event_id=events[7].id, guest_id=guests[23].id, status="Pending", channel="Email", date_invited=date(2026, 5, 10)),
    ]
    db.session.add_all(invitations)
    db.session.commit()
